### ISSUE TITLE
Music 에러

### ISSUE THREAD

**Issue by FKgk** [501Pb/DJ_Keyboard#10]
<img width="350" alt="Error1" src="https://user-images.githubusercontent.com/40608930/69492563-ceeb9000-0ee7-11ea-8b43-5a78c6470c5d.png">
<img width="1087" alt="Error2" src="https://user-images.githubusercontent.com/40608930/69492564-ceeb9000-0ee7-11ea-8762-9efe4d4366b9.png">

해당 부분에서 오류 발생했습니다.
@Phaskal 확인 부탁드립니다.

첫 번째 에러는 music이 선언 되어 있지 않는데 사용했습니다.
두 번째 에러는 포인터가 아닌데 new로 동적할당을 했습니다.

[PR #9 ](https://github.com/501Pb/DJ_Keyboard/pull/9#issue-344888870) 확인해주세요

**Comment by Phaskal** [comment]
new를 지우면 해결됩니다! 죄송합니다
