### ISSUE TITLE
thread가 계속 돌아가네요

### ISSUE THREAD

**Issue by FKgk** [501Pb/DJ_Keyboard#12]
https://github.com/501Pb/DJ_Keyboard/blob/e1bf47865049f353ac47e95750f03c528b87107f/keyboard/keyboard/music.cpp#L29
요 부분에서 끝나야 하는데, 끝나지 않습니다
playing이 false로 바뀌는 부분이 어디인지 모르겠습니다.
언제 끝나야 하나요?
@Phaskal

**Comment by Phaskal** [comment]
music.music_stop()을 호출하면 종료합니다. 아직 코드를 넣지 않았나 보군요

**Comment by FKgk** [comment]
오홍 한줄 짜리 코드는 헤더파일에 정의했군요
알겠습니당
