### ISSUE TITLE
녹음 filepath

### ISSUE THREAD

**Issue by Phaskal** [501Pb/DJ_Keyboard#13]
![image](https://user-images.githubusercontent.com/25507486/69862282-69c7de00-12dd-11ea-88f3-3ffa898ebacc.png)

종료시 filepath라고 뜨는데 원래 녹음 파일 명이 filepath인건가요?

**Comment by kimziou77** [comment]
아뇹 이거 game over 화면 함수에 임시로 올려놓은 filepath입니당
현재는 수정되어있네여
