### ISSUE TITLE
backspace error

### ISSUE THREAD

**Issue by kimziou77** [501Pb/DJ_Keyboard#15]
![image](https://user-images.githubusercontent.com/41179265/69894996-5c593500-136b-11ea-8659-08abeddcbc0f.png)

**Comment by FKgk** [comment]
https://github.com/501Pb/DJ_Keyboard/blob/9b9cf731c3a4c1cd81388ef4f7ce516184e81f9e/keyboard/keyboard/DJ_KeyBoard.cpp#L219

예외 처리 해줬습니다.
사진만 보면 무슨 에러인지 모르니, 설명도 넣어주세요

**Comment by kimziou77** [comment]
제목에 적어놨습니당 제목확인해주세용 ㅜㅜ 제곧내

**Comment by FKgk** [comment]
아항 그렇군요
감사합니당
