### ISSUE TITLE
irrKlang 사용시 문자열 출력

### ISSUE THREAD

**Issue by FKgk** [501Pb/DJ_Keyboard#6]
https://github.com/501Pb/DJ_Keyboard/blob/280199fc600e78040de604ec3ac2ab831726e7f9/keyboard/keyboard/Recording.cpp#L56

엔진을 만들기 위해 위 코드를 실행하면

```
irrKlang sound library version 1.6.0
Loaded plugin: ikpflac.dll
Loaded plugin: ikpmp3.dll
Using DirectSound8 driver
```

위와 같은 문자열을 출력한다. 때문에 엔진 생성 후에 Init를 하면 좋을 것 같습니다.

example:

![image](https://user-images.githubusercontent.com/40608930/68539035-f0655b80-03c0-11ea-92c8-7f26c859bb4b.png)

**Comment by Phaskal** [comment]
windows를 include 한뒤 os.system('cls')를 사용하면 화면이 지워지므로 이후에 메인화면을 띄우면 해결됩니다

**Comment by kimziou77** [comment]
@kwonnaseong check this issue!

**Comment by FKgk** [comment]
해당 이슈는 누군가 수정해 주었습니다.
init 후 각 쓰레드로 엔진을 생성하고 마지막에 cls로 전부 삭제하여 해결했습니다.

**Comment by kimziou77** [comment]
익명의 알파카가 해당글을 수정하였습니다 b
